version: "3"

#NETWORK
networks:
  my-network:
    driver: bridge

#VOLUMES
volumes: 
  dir-site:
    driver_opts: 
      device: ~/mycode/sites/
      o: bind
      type: ntfs

services:
  my-php:
    container_name: php-product
    build: 
      dockerfile: Dockerfile
      context: ./php/
    hostname: php
    restart: always
    networks:
      - my-network
    volumes:
      - dir-site:/home/sites
  my-httpd:
    container_name: c-httpd01
    image: "httpd:latest"
    hostname: httpd
    restart: always
    networks:
      - my-network
    volumes:
      - dir-site:/home/sites/
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports: 
      - "8000:80"
      - "443:443"
  my-mysql:
    container_name: mysql-product
    image: "mysql:latest"
    hostname: mysql
    restart: always
    networks:
      - my-network
    volumes:
      - ./db:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=123abc
      - MYSQL_DATABASE=db_site
      - MYSQL_USER=site_user
      - MYSQL_PASSWORD=site_password


